name: Zig build

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: korandoru/setup-zig@v1
        with:
          zig-version: master
      
      
      - name: Build - Zig test
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: zig build test --summary all -freference-trace

      - name: Build Summary
        run: zig build --summary all -freference-trace
