name: Zig build

on: [push, pull_request]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        runs-on: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: master
      
      
      - name: Build - Zig test
        run: zig build test -freference-trace

      - name: Build Summary
        run: zig build -fsummary -freference-trace
      
      - name: Build Summary (x86-windows-gnu)
        if: startsWith(matrix.runs-on, 'windows')
        run: zig build -fsummary -freference-trace -Dtarget=x86-windows

      - name: Build Summary (arm64-windows-gnu)
        if: startsWith(matrix.runs-on, 'windows')
        run: zig build -fsummary -freference-trace -Dtarget=aarch64-windows
      
      - name: Build Summary (arm64-macos)
        if: startsWith(matrix.runs-on, 'macos')
        run: zig build -fsummary -freference-trace -Dtarget=aarch64-macos
      
      - name: Build Summary (arm64-linux-gnu)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: zig build -fsummary -freference-trace -Dtarget=aarch64-linux-gnu

      - name: Build Summary (arm64-linux-musl)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: zig build -fsummary -freference-trace -Dtarget=aarch64-linux
      
      - name: Build Summary (riscv64-linux-musl)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: zig build -fsummary -freference-trace -Dtarget=riscv64-linux
      
      - name: Build Summary (powerpc64-linux-musl)
        if: startsWith(matrix.runs-on, 'ubuntu')
        run: zig build -fsummary -freference-trace -Dtarget=powerpc64-linux
